version: 2

run:
  timeout: 10m
  allow-parallel-runners: true
  modules-download-mode: readonly

issues:
  # don't exclude the default set of lint
  exclude-use-default: false
  exclude-rules:
  - path: (.+)_test\.go
    linters:
    - lll
    - errcheck
  - path: "test/*"
    linters:
    - goconst
    - lll
    - unparam
  - path: "controllers/*"
    linters:
    - lll
  - path: "api/*"
    linters:
    - lll
  - path: "const/*"
    linters:
    - lll

linters:
  disable-all: false
  enable:
  - dupl
  - errcheck
  - copyloopvar
  - goconst
  - gocyclo
  - govet
  - ineffassign
  - lll
  - misspell
  - nakedret
  - prealloc
  - staticcheck
  - unconvert
  - unparam
  - unused
  - gocritic

linters-settings:
  lll:
    line-length: 130 # or any length you prefer

formatters:
  enable:
  - gofmt
  - goimports
