# +-------------------------------------------------------------------+
# | Copyright (c) 2025, 2026 IBM Corp.                                |
# | SPDX-License-Identifier: Apache-2.0                               |
# +-------------------------------------------------------------------+

name: Build Image

on:
  workflow_dispatch:
  push:
    branches:
    - main

permissions:
  contents: read
  packages: write # Crucial for pushing to ghcr.io

env:
  GOTOOLCHAIN: auto

jobs:
  build:
    uses: ibm-aiu/spyre-operator-actions/.github/workflows/build-image.yaml@main
    with:
      image_name: spyre-webhook-validator
      pre_build_command: make vendor
